<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Company1Table" Member="Company1Tables">
    <Type Name="Company1Table">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmployeeNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Company1Table_EmployeeTable" Member="EmployeeTables" ThisKey="Id" OtherKey="Cid" Type="EmployeeTable" />
    </Type>
  </Table>
  <Table Name="dbo.AdminTable" Member="AdminTables">
    <Type Name="AdminTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdminEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContactTable" Member="ContactTables">
    <Type Name="ContactTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CVTable" Member="CVTables">
    <Type Name="CVTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Full Name]" Member="Full_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Apply For]" Member="Apply_For" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Upload your Pic]" Member="Upload_your_Pic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Upload your resume]" Member="Upload_your_resume" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ITjobPostTable" Member="ITjobPostTables">
    <Type Name="ITjobPostTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Post" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JobPostTable" Member="JobPostTables">
    <Type Name="JobPostTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostName" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Duration" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Stipend" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeTable" Member="EmployeeTables">
    <Type Name="EmployeeTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmpployeeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JobProfile" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Review" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Linkedlink" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmpPic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Company1Table_EmployeeTable" Member="Company1Table" ThisKey="Cid" OtherKey="Id" Type="Company1Table" IsForeignKey="true" />
    </Type>
  </Table>
</Database>